In [130]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers

In [131]:
print(pd.__version__)
print(tf.__version__)

1.2.4
2.4.1


In [154]:
# 加载训练数据
df = pd.read_csv("20210901-尾页付费样本-训练数据.csv")
df.head(10)

ds = tf.data.Dataset.from_tensor_slices(df.head(1).to_dict(orient = 'list'))
print(list(ds.as_numpy_iterator()))

def make_dataset(data_df, label_df, epochs = 1, shuffle = True, batch_size = 1):
    dataset = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))
    if shuffle:
        dataset = dataset.shuffle(1)
    dataset = dataset.repeat(epochs).batch(batch_size)
    
    return dataset

label_df = df[['label']].head(10)
del df['label']
data_df = df.head(10)



train_data = make_dataset(data_df, label_df)
print(type(train_data))

dmp_sex = tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_identity(
    key='dmp_sex', num_buckets=5, default_value=0))
columns = [dmp_sex]

for x ,y in train_data.take(10):
#     print(x)
    print(tf.keras.layers.DenseFeatures(dmp_sex)(x).numpy())

[{'label': 0, 'select_sex': 0, 'dmp_sex': 2, 'dmp_age': 31, 'dmp_city': b'1', 'dmp_education': 1010165000000010009, 'dmp_price': b'3999', 'dmp_model': b'1010107000000001153', 'user_state': 2, 'first_preference': 1, 'first_weight': 9582.75, 'second_preference': 0, 'second_weight': 0.0, 'freetype': 1, 'categoryid': 20019, 'subcategoryid': 20026, 'allwords': 11571526, 'vipwords': b'11627060', 'avgbuy': 21332}]
<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>
[[0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[1. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[0. 1. 0. 0. 0.]]
[[0. 0. 1. 0. 0.]]
[[0. 1. 0. 0. 0.]]


In [153]:
data_df

select_sex  dmp_sex  dmp_age dmp_city        dmp_education dmp_price  \
0           0        2       31        1  1010165000000010009      3999   
1           0        2       18        4                    0      1499   
2           0        2       14        2  1010165000000010004      1298   
3           0        2       39        1  1010165000000010004      6499   
4           0        0        0        1                    0      2299   
5           0        2       13        2  1010165000000010009         0   
6           0        2       30        0  1010165000000010008    999999   
7           0        1       32        3  1010165000000010004         0   
8           0        2       17        2  1010165000000010007      2999   
9           0        1       46        3  1010165000000010010      1299   

             dmp_model  user_state  first_preference  first_weight  \
0  1010107000000001153           2                 1       9582.75   
1  1010107000000001079           2                 2       6827.04   
2  1010107000000001102           1                 1        621.28   
3  1010107000000001421           1                 2        283.56   
4  1010107000000001224           2                 2      19323.90   
5  1010107000000001079           2                 2      50737.80   
6  1010107000000001153           2                 2     223071.00   
7  1010107000000001153           2                 1      15649.10   
8  1010107000000001079           2                 2       8422.20   
9  1010107000000001288           2                 2      14190.40   

   second_preference  second_weight  freetype  categoryid  subcategoryid  \
0                  0           0.00         1       20019          20026   
1                  1        2830.54         2       30013          30015   
2                  2           7.30         2       30013          30015   
3                  0           0.00         2       30013          30017   
4                  0           0.00         2       30008          30010   
5                  0           0.00         2       30020          30028   
6                  0           0.00         2       30013          30017   
7                  0           0.00         1       20001          20002   
8                  0           0.00         2       30020          30028   
9                  0           0.00         2       30013          30017   

   allwords  vipwords  avgbuy  
0  11571526  11627060   21332  
1   2199674   4391429   23815  
2   2199674   4391429   23815  
3  12031601  12044623   32595  
4   1226949   1173250    2899  
5    749828   1310976    5137  
6   2516120   4904666   44457  
7   2690921   2598316     425  
8    624895    630664    1131  
9   4902877   4872859    3465