In [13]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.4.1


In [5]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

11493376/11490434 [==============================] - 8s 1us/step
Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4812 - accuracy: 0.8615
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1475 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 2s 974us/step - loss: 0.1099 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0863 - accuracy: 0.9731
Epoch 5/5
313/313 [==============================] - 1s 1ms/step - loss: 0.0738 - accuracy: 0.9766


[0.07384887337684631, 0.9765999913215637]

In [16]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
price = tf.feature_column.numeric_column('price')

column = [price]

model = tf.keras.models.Sequential([
    tf.keras.layers.DenseFeatures(column),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# train_data_dict = np.asarray([{"price":12},{"price":55},{"price":987}])

# y_train_ary =  np.asarray([1,0,2])

# model.fit(train_data_dict, y_train_ary, epochs=5)

# model.summary()

In [26]:
toy_data = {'movie': [[0], [1], [0], [1]], 'user': [[10], [12], [12], [10]]}
dataset = tf.data.Dataset.from_tensor_slices(toy_data).batch(2)
for x in dataset:
    print(x)
    
def make_model():
    inp_movie = tf.keras.Input(shape=(1,), name='movie')
    inp_user = tf.keras.Input(shape=(1,), name='user')
    
    movie_embedding = tf.keras.layers.Dense(
            units=40, activation=tf.keras.layers.Activation("relu"))(inp_movie)
    user_embedding = tf.keras.layers.Dense(
            units=40, activation=tf.keras.layers.Activation("relu"))(inp_user)
    combined = tf.concat([movie_embedding, user_embedding], 1)
    output = tf.keras.layers.Dense(
            units=1, activation=tf.keras.layers.Activation("sigmoid"))(combined)
    model = tf.keras.Model(inputs=[inp_movie, inp_user], outputs=output)
    return model

model = make_model()


for x in dataset:
    print(model(x))

{'movie': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [1]])>, 'user': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [12]])>}
{'movie': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[0],
       [1]])>, 'user': <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[12],
       [10]])>}


TypeError: Dimension value must be integer or None or have an __index__ method, got value ''price'' with type '<class 'str'>'